FROM rocker/shiny:devel

MAINTAINER Tim M.Schendzielorz "tim.schendzielorz@googlemail.com"
 
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libxml2-dev \
  libcairo2-dev \
  libudunits2-dev \
  libv8-dev \
  libsqlite3-dev \
  libmariadbd-dev \
  libmariadbclient-dev \
  default-libmysqlclient-dev \
  libpq-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  libssh2-1-dev \
  unixodbc-dev \
  && install2.r --error \
    --deps TRUE \
    tidyverse \
    dplyr \
    devtools \
    formatR \
    remotes \
    selectr \
    caTools \
	BiocManager \&&
	R -e "install.packages(c('shiny', 'flexdashboard', 'dbplyr','lubridate','DBI', 'RMySQL', 'pool', 'stringi'),dependencies = TRUE)" 

    


	
	
RUN mkdir -p /bin
COPY Dashboard_kursnet_ranking.Rmd   /bin/Dashboard_kursnet_ranking.Rmd   
COPY Logo-karriere-tutor.png         /bin/Logo-karriere-tutor.png

# make all app files readable (solves issue when dev in Windows, but building in Ubuntu)
RUN chmod -R 755 /bin

EXPOSE 3838

CMD ["R", "-e", "rmarkdown::run('/bin/Dashboard_kursnet_ranking.Rmd', shiny_args = list(port = 3838, host = '0.0.0.0'))"]
